### ISSUE TITLE
Working with webpack and NPM

### ISSUE THREAD

**Issue by facultymatt** [TomNeyland/angular-dc#58]
Anyone have luck getting this working with webpack and NPM? 

With the following code: 

```
require('angular-dc');
angular.module('app', ['angularDc'])
```

I get the following error

```
angular.js:68Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module angularDc due to:
Error: [$injector:nomod] Module 'angularDc' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=angularDc
    at http://localhost:3000/index.js:8421:12
    at http://localhost:3000/index.js:10435:17
    at ensure (http://localhost:3000/index.js:10359:38)
```

**Comment by sallespro** [comment]
did you browserify your required module ?
